version: "3.9"
networks:
  localhost:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 127.0.0.1/24
  foonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8000:3030"
    volumes:
      - ./:/app
      - /app/gateway/node_modules
    env_file:
      - ./gateway/.env

  service:
    build: ./service
    container_name: service
    volumes:
      - ./:/app
      - /app/service/node_modules
    env_file:
      - ./service/.env
  client:
    depends_on:
      - gateway
    build: ./client
    container_name: client
    ports:
      - 9000:80
    volumes:
      - ./:/app
      - /app/client/node_modules
    env_file:
      - ./client/.env

  mongo_rs_1:
    build:
      context: ./mongo_rs/
      dockerfile: Dockerfile
      target: mongo_rs_1_image
    restart: always
    env_file:
      - ./mongo_rs/.env
    environment:
      - CA_PASS=jnjnjnj
    expose:
      - 27017
    networks:
      foonet:
        ipv4_address: 172.22.1.13
    command: mongod --bind_ip 127.0.0.1,172.22.1.13  --replSet mongo-rs --tlsMode requireTLS --tlsCertificateKeyFile mongo_rs_1.pem --tlsCAFile rs_ca_private.crt  --clusterAuthMode x509


  mongo_rs_2:
    build:
      context: ./mongo_rs/
      dockerfile: Dockerfile
      target: mongo_rs_2_image
    restart: always
    env_file:
      - ./mongo_rs/.env
    expose:
      - 27017
    networks:
      foonet:
        ipv4_address: 172.22.1.23
    command:
      - /bin/sh
      - -c
      - exec /usr/local/bin/init.sh
    command: mongod --bind_ip 127.0.0.1,172.22.1.23  --replSet mongo-rs --tlsMode requireTLS --tlsCertificateKeyFile mongo_rs_2.pem --tlsCAFile rs_ca_private.crt  --clusterAuthMode x509


  mongo_rs_3:
    build:
      context: ./mongo_rs/
      dockerfile: Dockerfile
      target: mongo_rs_3_image
    restart: always
    env_file:
      - ./mongo_rs/.env
    expose:
      - 27017
    networks:
      foonet:
        ipv4_address: 172.22.1.33
    command: mongod --bind_ip 127.0.0.1,172.22.1.33  --replSet mongo-rs --tlsMode requireTLS --tlsCertificateKeyFile mongo_rs_3.pem --tlsCAFile rs_ca_private.crt  --clusterAuthMode x509


  init_mongo_replicas:
    build:
      context: ./mongo_rs/
      dockerfile: Dockerfile
      target: mongo_replica_init
    restart: "no"
    networks:
      foonet:
        ipv4_address: 172.22.1.36
    depends_on:
      - mongo_rs_1
      - mongo_rs_2
      - mongo_rs_3
    env_file:
      - ./mongo_rs/.env
    command:
      - /bin/sh
      - -c
      - exec /usr/local/bin/rs_init.sh


